GET http://localhost:8080/api/content

###
POST http://localhost:8080/api/content
Content-Type: application/json

{
    "id": 2,
    "title": "Second blog",
    "desc": "Desc of second blog",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": "2023-04-15T17:00:23.2822432",
    "dateUpdated": null,
    "url": ""
}

###update
PUT http://localhost:8080/api/content/2
Content-Type: application/json

{
"id": 2,
"title": "Second Blog",
"desc": "Desc of second blog",
"status": "IDEA",
"contentType": "ARTICLE",
"dateCreated": "2023-04-15T17:00:23.2822432",
"dateUpdated": null,
"url": ""
}

###Delete
DELETE http://localhost:8080/api/content/2